- name: Install geerlingguy.pip
  community.general.ansible_galaxy_install:
    type: role
    name: geerlingguy.pip
- name: Install geerlingguy.docker_arm
  community.general.ansible_galaxy_install:
    type: role
    name: geerlingguy.docker_arm
