# nb. does not update entry in /etc/hosts
# if this causes issues then add entry here to update hosts file
- name: set hostname
  become: true
  tags: [ always ]
  ansible.builtin.hostname:
    name: "{{ hostname }}"