- name: install linux useful binaries
  become: true
  ansible.builtin.apt:
    update_cache: true
    pkg:
    - sshpass
    - vim
    - git
    - mosquitto
    - mosquitto-clients
    - python3-pip
    state: latest

- name: install minikube deb
  become: true
  ansible.builtin.apt:
    deb: https://storage.googleapis.com/minikube/releases/latest/minikube_latest_arm64.deb