- name: install linux useful binaries
  become: yes
  apt:
    update_cache: true
    pkg:
    - sshpass
    - vim
    - git
    - mosquitto
    - mosquitto-clients
    - python3-pip
    state: latest