---
- name: docker compose update
  hosts: localhost
  tasks:
    - name: stop docker containers
      community.docker.docker_compose:
        project_src: "{{ compose_file_dir }}"
        files: "{{ docker_compose_files }}"
        state: absent
    - name: pull latest image and restart containers
      community.docker.docker_compose:
        files: "{{ docker_compose_files }}"
        project_src: "{{ compose_file_dir }}"
        pull: true
        state: present
