# based upon https://pimylifeup.com/rasberry-pi-unifi/
- name: pi unifi setup
  hosts: <ip addr>
  become_user: root
  become: true
  tasks:
    - name: install jdk 8 rng-tools
      apt:
        update_cache: true
        pkg:
        - openjdk-8-jre-headless
        - rng-tools
        state: latest
    - name: replace content in /etc/default/rng-tools-debian
      ansible.builtin.shell:
        cmd: sed -i 's/#HRNGDEVICE=/dev/hwrng/HRNGDEVICE=/dev/hwrng/' rng-tools-debian
        chdir: /etc/default/
    - name: replace file  /etc/apt/preferences.d/99stretch-mongodb.pref
      ansible.builtin.copy:
        src: pi-files/99stretch-mongodb.pref
        dest:  /etc/apt/preferences.d/
    - name: replace content in /etc/default/rng-tools-debian
      ansible.builtin.shell:


        echo "deb http://archive.raspbian.org/raspbian stretch main" | sudo tee /etc/apt/sources.list.d/stretch_mongodb.list

