- name: debian setup
  hosts: 
  become_user: root
  become: true
  tasks:
    - name: install 
      apt:
        update_cache: true
        pkg:
        - sshpass
        - vim
        - git
        - mosquitto
        - mosquitto-clients
        state: latest
