# need to install ansible and register ssh key before running
# nb. need to set hostname var for set_hostname role
# recognised tags, pi0|pi4
- name: setup pi
  hosts: "{{ pi_ip }}"
  roles:
    - role: set_hostname
      tags: [ firstrun, hostname ]
    - role: apt_update
      tags: [ firstrun, update ]
    - role: install_binaries_debian
      tags: [ firstrun, binaries ]
    - role: debian_dev_setup
      tags: [ pi4, devsetup ]
    - role: use_builtin.pip
      vars:
        module: wakeonlan
      tags: [ never, pi0, wakeonlan ]
    - role: install_docker_arm_roles
      tags: [ never, docker_arm, pi4 ]
    - role: nvm
      tags: [ firstrun, nvm ]