# need to install ansible and register ssh key before running
- name: setup pi0
  hosts: "{{ pi0_ip }}"
  roles:
    - role: set_hostname
      vars:
        hostname: pi-zero
    - role: apt_update
    - role: install_binaries_debian