# need to install ansible and register ssh key before running
- name: setup pi4
  hosts: localhost
  roles:
    - role: apt_update
    - role: install_docker_arm_roles
    - role: install_binaries_debian