# TODO make generic and rename file
---
- name: install unifi controller and pihole
  hosts: "{{ dest_pi_server }}"
  vars:
    home: "{{ lookup('ansible.builtin.env', 'HOME') }}"
    docker_file_name: docker-compose-unifi-pihole.yml
    src_docker_file: "docker_files/{{ docker_file_name }}"
    dest_docker_dir: "{{ 'docker_files' if dest_pi_server == 'localhost' else home + '/docker_files' }}"
    dest_docker_file: "{{ dest_docker_dir }}/{{ docker_file_name }}"
  tasks:
    - name: create destination directory on remote
      ansible.builtin.file:
       path: "{{ dest_docker_dir }}"
       state: directory
      when: dest_pi_server != 'localhost'
    - name: copy docker-compose file  "{{ dest_docker_file }}"
      ansible.builtin.copy:
        src: "{{ src_docker_file }}"
        dest: "{{ dest_docker_file }}"
      when: dest_pi_server != 'localhost'
    - name: docker deploy remote
      community.docker.docker_compose:
        project_src: "{{ dest_docker_dir }}"
        state: present
        files: "{{ docker_file_name }}"
        