---
roles:
  - name: geerlingguy.pip
    src: https://github.com/geerlingguy/ansible-role-pip.git
    version: 3.0.0
  - name: geerlingguy.docker
    src: https://github.com/geerlingguy/ansible-role-docker_arm.git
    version: 5.0.0